<?php include 'config/database.php'; ?>
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <title>OFİS HAL - Satış Faturası</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/dark-theme.css" id="theme-css">
    <style>
        .fatura-table input { width: 100%; padding: 6px; border: 1px solid #334155; border-radius: 4px; text-align: center; background: #0f3460; color: white; }
        .fatura-table input:focus { outline: 2px solid #e94560; background: #1a4a7a; }
        .fatura-table input::placeholder { color: #88a0c0; }
        .fatura-table .urun-ad, .fatura-table .birim, .fatura-table .tutar { background: #0f3460; }
        .modal-calc { display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.7); justify-content: center; align-items: center; z-index: 10000; }
        .modal-calc-content { background: #16213e; padding: 20px; border-radius: 12px; width: 350px; border: 1px solid #2a2a3a; }
        .calc-buttons { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; margin-top: 10px; }
        .calc-buttons button { padding: 12px; font-size: 18px; }
        .toast-notify { position: fixed; bottom: 20px; right: 20px; background: #22c55e; color: white; padding: 10px 20px; border-radius: 8px; z-index: 9999; opacity: 0; transition: 0.3s; }
        .list-group-item { background: #16213e; border-color: #2a2a3a; color: white; cursor: pointer; }
        .list-group-item:hover { background: #0f3460; }
        .musteri-modal { position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.7); display: flex; justify-content: center; align-items: center; z-index: 10001; }
        .musteri-modal-content { background: #16213e; padding: 20px; border-radius: 12px; width: 500px; border: 1px solid #2a2a3a; }
        .btn-excel { background: #059669; color: white; }
        .btn-pdf { background: #dc2626; color: white; }
        .theme-toggle { position: fixed; bottom: 20px; right: 20px; width: 50px; height: 50px; border-radius: 50%; font-size: 24px; background: #0f3460; border: 1px solid #2a2a3a; color: white; cursor: pointer; z-index: 9999; }
        #refNoGoster { color: #e94560; font-weight: bold; }
        #malToplam, #kdvTutar, #genelToplam { color: #e94560; font-weight: bold; }
        kbd { background: #1a1a2e; color: #e2e2e2; border: 1px solid #2a2a3a; padding: 3px 8px; border-radius: 6px; }
    </style>
</head>
<?php
$duzenleNo = $_GET['duzenle'] ?? '';
$duzenleData = null;
if ($duzenleNo) {
    $stmt = $pdo->prepare("SELECT f.*, m.kod as musteri_kod, m.ad as musteri_adi, m.vergi_no, m.efatura_tipi, m.iskonto_orani FROM faturalar f JOIN musteriler m ON f.musteri_id = m.id WHERE f.fatura_no = ?");
    $stmt->execute([$duzenleNo]);
    $duzenleData = $stmt->fetch(PDO::FETCH_ASSOC);
    if ($duzenleData) {
        $satirStmt = $pdo->prepare("SELECT fs.*, u.kod as urun_kod, b.birim_adi FROM fatura_satirlari fs LEFT JOIN urunler u ON fs.urun_id = u.id LEFT JOIN birimler b ON u.birim_ref = b.ref_id WHERE fs.fatura_id = ? ORDER BY fs.sira");
        $satirStmt->execute([$duzenleData['id']]);
        $duzenleData['satirlar'] = $satirStmt->fetchAll(PDO::FETCH_ASSOC);
    }
}
?>
<body>
<div class="container mt-3">
    <div class="card"><div class="card-header"><h3>🧾 FATURA KES</h3></div><div class="card-body">
        <div class="row">
            <div class="col-md-8"><label>Müşteri Kodu <kbd>F2</kbd></label><div class="input-group"><input type="text" id="musteriKod" class="form-control" placeholder="Kod veya isim yaz"><button class="btn btn-secondary" onclick="musteriAraModal()">🔍 Ara</button></div><div id="musteriBilgi" class="mt-2 p-2 bg-secondary bg-opacity-25 rounded"></div></div>
            <div class="col-md-4"><label>Fatura No</label><input type="text" id="faturaNo" class="form-control"><small>Ref No: <span id="refNoGoster">-</span></small><label class="mt-2">Tarih</label><input type="date" id="tarih" class="form-control" value="<?= date('Y-m-d') ?>"><label>Vade (Gün)</label><input type="number" id="vade" class="form-control" value="0"></div>
        </div>
        <div class="row mt-3"><div class="col-md-6"><button id="toggleOdeme" class="btn btn-warning">💰 Peşin <kbd>F7</kbd></button><input type="hidden" id="odemeTipi" value="Peşin"></div><div class="col-md-6 text-end"><label>KDV (%)</label><input type="number" id="kdvOran" class="form-control w-25 d-inline" value="1"></div></div>
        <h4 class="mt-4">Ürünler <kbd>F3</kbd></h4>
        <div class="table-responsive"><table class="table table-bordered fatura-table" id="faturaTable"><thead class="table-secondary"><tr><th>Ürün Kodu</th><th>Ürün Adı</th><th>Birim</th><th>Miktar</th><th>Fiyat</th><th>İskonto%</th><th>Tutar</th></tr></thead>
        <tbody><tr class="urun-satir"><td><input type="text" class="urun-kod" placeholder="Kod"></td><td><input type="text" class="urun-ad" readonly></td><td><input type="text" class="birim" readonly></td><td><input type="number" class="miktar" step="any" value="" placeholder="0"></td><td><input type="number" class="fiyat" step="any" value="" placeholder="0"></td><td><input type="number" class="iskonto" value="0"></td><td><input type="text" class="tutar" readonly></td></tr></tbody>
        </table></div>
        <div class="row mt-3"><div class="col-md-6 offset-md-6"><table class="table"><tr><td><strong>Mal Toplam:</strong></td><td id="malToplam" class="text-end">0.00</td></tr>
        <tr><td><strong>KDV (%<span id="kdvYuzde">1</span>):</strong></td><td id="kdvTutar" class="text-end">0.00</td></tr>
        <tr class="table-success"><td><strong>GENEL TOPLAM:</strong></td><td id="genelToplam" class="text-end fs-4">0.00</td></tr></table></div></div>
        <div class="row"><div class="col-md-4"><button id="kaydetBtn" class="btn btn-success w-100">💾 F1 / F10 KAYDET</button></div><div class="col-md-4"><button id="excelBtn" class="btn btn-excel w-100" style="display:none;">📎 Excel</button></div><div class="col-md-4"><button id="pdfBtn" class="btn btn-pdf w-100" style="display:none;">📄 PDF</button></div></div>
    </div></div>
</div>

<!-- Hesap Makinesi Modal -->
<div id="calcModal" class="modal-calc"><div class="modal-calc-content"><h4>🧮 Hesap Makinesi <kbd>ESC</kbd></h4><input type="text" id="calcInput" readonly class="form-control" style="font-size:24px;text-align:right;"><div class="calc-buttons"><button onclick="calcPress('7')">7</button><button onclick="calcPress('8')">8</button><button onclick="calcPress('9')">9</button><button onclick="calcPress('/')">/</button><button onclick="calcPress('4')">4</button><button onclick="calcPress('5')">5</button><button onclick="calcPress('6')">6</button><button onclick="calcPress('*')">*</button><button onclick="calcPress('1')">1</button><button onclick="calcPress('2')">2</button><button onclick="calcPress('3')">3</button><button onclick="calcPress('-')">-</button><button onclick="calcPress('0')">0</button><button onclick="calcPress('.')">.</button><button onclick="calcPress('=')">=</button><button onclick="calcPress('+')">+</button><button onclick="calcPress('C')">C</button><button onclick="closeCalculator()">Kapat</button></div></div></div>

<!-- Ürün Modal -->
<div id="urunModal" class="modal-calc" style="display:none;"><div class="modal-calc-content" style="width:600px;"><h4>📦 Ürün Ara / Düzenle</h4><input type="text" id="urunAra" class="form-control" placeholder="Ürün ara..." onkeyup="urunListele()"><div id="urunListesi" class="list-group mt-2" style="max-height:250px; overflow-y:auto;"></div><hr><div class="row"><div class="col-4"><label>Kod</label><input type="text" id="urunKod" class="form-control"></div><div class="col-5"><label>Ad</label><input type="text" id="urunAd" class="form-control"></div><div class="col-3"><label>Birim</label><select id="urunBirimRef" class="form-control"><?php $b=$pdo->query("SELECT ref_id,birim_adi FROM birimler ORDER BY birim_adi")->fetchAll(); foreach($b as $bb) echo "<option value='{$bb['ref_id']}'>{$bb['birim_adi']} ({$bb['ref_id']})</option>"; ?></select><button class="btn btn-sm btn-secondary mt-1 w-100" onclick="yeniBirimEkle()">+ Yeni Birim</button></div></div><div class="row mt-2"><div class="col-4"><label>KDV</label><input type="number" id="urunKdv" class="form-control" value="1"></div></div><div class="row mt-3"><div class="col-6"><button class="btn btn-primary w-100" onclick="urunKaydet()">Kaydet</button></div><div class="col-6"><button class="btn btn-secondary w-100" onclick="urunModalKapat()">Kapat</button></div></div></div></div>

<button class="theme-toggle" id="themeToggle" onclick="toggleTheme()">☀️</button>
<script src="assets/js/theme.js"></script>
<script>
function showToast(msg, isError) { let t=document.querySelector('.toast-notify'); if(!t){ t=document.createElement('div'); t.className='toast-notify'; document.body.appendChild(t); } t.textContent=msg; t.style.backgroundColor=isError?'#dc2626':'#22c55e'; t.style.opacity='1'; setTimeout(()=>t.style.opacity='0',2000); }
function calcPress(v) { let inp=document.getElementById('calcInput'); if(v==='C'){ window.calcExpr=''; inp.value='0'; }else if(v==='='){ try{ let r=eval(window.calcExpr); inp.value=r; window.calcExpr=r.toString(); }catch(e){ inp.value='Hata'; } }else{ if(!window.calcExpr || window.calcExpr==='0' && /[0-9]/.test(v)) window.calcExpr=v; else window.calcExpr+=v; inp.value=window.calcExpr; } }
function openCalculator() { let m=document.getElementById('calcModal'); if(m) m.style.display='flex'; document.getElementById('calcInput').value='0'; window.calcExpr=''; }
function closeCalculator() { document.getElementById('calcModal').style.display='none'; }
function addNewRow() { let tbody=document.querySelector('#faturaTable tbody'); if(!tbody) return; let row=document.createElement('tr'); row.className='urun-satir'; let isk=window.musteriIskonto||0; row.innerHTML='<td><input type="text" class="urun-kod" placeholder="Kod"></td><td><input type="text" class="urun-ad" readonly></td><td><input type="text" class="birim" readonly></td><td><input type="number" class="miktar" step="any" value="" placeholder="0"></td><td><input type="number" class="fiyat" step="any" value="" placeholder="0"></td><td><input type="number" class="iskonto" value="'+isk+'"></td><td><input type="text" class="tutar" readonly></td>'; tbody.appendChild(row); attachRowEvents(row); return row; }
function attachRowEvents(row) { row.querySelector('.urun-kod')?.addEventListener('keydown',e=>handleUrunKod(e,row)); row.querySelector('.miktar')?.addEventListener('keydown',e=>handleMiktar(e,row)); row.querySelector('.fiyat')?.addEventListener('keydown',e=>handleFiyat(e,row)); }
function handleUrunKod(e,row){ if(e.key==='Enter'){ e.preventDefault(); let k=row.querySelector('.urun-kod').value.trim(); if(k) fetchUrun(k,row,true); }else if(e.key==='ArrowDown'){ e.preventDefault(); let k=row.querySelector('.urun-kod').value.trim(); if(k) fetchUrun(k,row,false); let nr=row.nextElementSibling; if(!nr) nr=addNewRow(); setTimeout(()=>nr.querySelector('.urun-kod').focus(),50); }else if(e.key==='ArrowUp'){ e.preventDefault(); let k=row.querySelector('.urun-kod').value.trim(); if(k) fetchUrun(k,row,false); let pr=row.previousElementSibling; if(pr) pr.querySelector('.urun-kod').focus(); } }
function handleMiktar(e,row){ if(e.key==='Enter'){ e.preventDefault(); row.querySelector('.fiyat').focus(); }else if(e.key==='ArrowDown'){ e.preventDefault(); let nr=row.nextElementSibling; if(!nr) nr=addNewRow(); setTimeout(()=>nr.querySelector('.miktar').focus(),50); }else if(e.key==='ArrowUp'){ e.preventDefault(); let pr=row.previousElementSibling; if(pr) pr.querySelector('.miktar').focus(); } }
function handleFiyat(e,row){ if(e.key==='Enter'){ e.preventDefault(); hesaplaTutar(row); let nr=row.nextElementSibling; if(!nr) nr=addNewRow(); setTimeout(()=>nr.querySelector('.urun-kod').focus(),50); }else if(e.key==='ArrowDown'){ e.preventDefault(); hesaplaTutar(row); let nr=row.nextElementSibling; if(!nr) nr=addNewRow(); setTimeout(()=>nr.querySelector('.fiyat').focus(),50); }else if(e.key==='ArrowUp'){ e.preventDefault(); hesaplaTutar(row); let pr=row.previousElementSibling; if(pr) pr.querySelector('.fiyat').focus(); } }
function fetchUrun(kod,row,enterMod){ fetch('ajax/urun_getir.php?kod='+encodeURIComponent(kod)).then(r=>r.json()).then(data=>{ if(data.success){ row.querySelector('.urun-ad').value=data.ad; row.querySelector('.birim').value=data.birim_adi; row.querySelector('.miktar').value=''; row.querySelector('.fiyat').value=''; if(enterMod) row.querySelector('.miktar').focus(); showToast(data.ad+' eklendi'); }else{ if(confirm('"'+kod+'" kayıtlı değil. Yeni ürün eklemek ister misiniz?')) urunModalGoster(kod); } }); }
function hesaplaTutar(row){ let m=parseFloat(row.querySelector('.miktar').value)||0; let f=parseFloat(row.querySelector('.fiyat').value)||0; let i=parseFloat(row.querySelector('.iskonto').value)||0; let t=m*f; if(i>0) t=t*(1-i/100); row.querySelector('.tutar').value=t>0?t.toFixed(2):''; genelToplamHesapla(); }
function genelToplamHesapla(){ let toplam=0; document.querySelectorAll('.tutar').forEach(t=>{ let v=parseFloat(t.value); if(!isNaN(v) && v>0) toplam+=v; }); let kdv=parseFloat(document.getElementById('kdvOran').value)||1; let kdvT=toplam*kdv/100; let genel=toplam+kdvT; document.getElementById('malToplam').innerText=toplam.toFixed(2); document.getElementById('kdvTutar').innerText=kdvT.toFixed(2); document.getElementById('genelToplam').innerText=genel.toFixed(2); }
function musteriAra(aranan){ fetch('ajax/musteri_ara.php?q='+encodeURIComponent(aranan)).then(r=>r.json()).then(data=>{ if(data.length===1) musteriSec(data[0]); else if(data.length>1) musteriListeModal(data); else { document.getElementById('musteriBilgi').innerHTML='<span class="text-danger">Müşteri bulunamadı!</span>'; showToast('Müşteri bulunamadı',true); } }); }
function musteriSec(m){ document.getElementById('musteriKod').value=m.kod; document.getElementById('musteriBilgi').innerHTML='<strong>'+m.ad+'</strong><br>Vergi No: '+(m.vergi_no||'-')+' - '+m.efatura_tipi+'<br>🏷️ İskonto: %'+(m.iskonto_orani||0); showToast('Müşteri bulundu: '+m.ad); window.musteriIskonto=m.iskonto_orani||0; document.querySelectorAll('.iskonto').forEach(i=>i.value=window.musteriIskonto); }
function musteriListeModal(liste){ let html='<div id="musteriListeModal" class="musteri-modal"><div class="musteri-modal-content"><h4>Müşteri Seçin</h4><div id="modalListe">'; liste.forEach(m=>{ html+='<div class="list-group-item list-group-item-action" onclick="musteriSec('+JSON.stringify(m)+')"><strong>'+m.kod+'</strong> - '+m.ad+'<br><small>'+(m.vergi_no||'')+' | '+m.efatura_tipi+' | İskonto: %'+(m.iskonto_orani||0)+'</small></div>'; }); html+='</div><button class="btn btn-secondary mt-2" onclick="this.parentElement.parentElement.remove()">Kapat</button></div></div>'; document.body.insertAdjacentHTML('beforeend',html); }
function musteriAraModal(){ let d=document.getElementById('musteriKod').value.trim(); if(d.length<2) showToast('En az 2 karakter',true); else fetch('ajax/musteri_ara.php?q='+encodeURIComponent(d)).then(r=>r.json()).then(data=>{ if(data.length) musteriListeModal(data); else showToast('Müşteri bulunamadı',true); }); }
function urunModalGoster(yeniKod){ let m=document.getElementById('urunModal'); if(m) m.style.display='flex'; if(yeniKod){ document.getElementById('urunKod').value=yeniKod; document.getElementById('urunAd').focus(); } urunListele(); }
function urunListele(){ fetch('ajax/urun_listele.php').then(r=>r.json()).then(data=>{ let liste=document.getElementById('urunListesi'); if(!liste) return; liste.innerHTML=''; data.forEach(u=>{ let d=document.createElement('div'); d.className='list-group-item list-group-item-action'; d.innerHTML='<strong>'+u.kod+'</strong> - '+u.ad+' ('+u.birim_adi+') KDV:'+u.varsayilan_kdv+'%'; d.onclick=()=>{ document.getElementById('urunKod').value=u.kod; document.getElementById('urunAd').value=u.ad; document.getElementById('urunBirimRef').value=u.birim_ref; document.getElementById('urunKdv').value=u.varsayilan_kdv; }; liste.appendChild(d); }); }); }
function urunKaydet(){ let kod=document.getElementById('urunKod').value; let ad=document.getElementById('urunAd').value; let br=document.getElementById('urunBirimRef').value; let kdv=document.getElementById('urunKdv').value; fetch('ajax/urun_kaydet.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'kod='+encodeURIComponent(kod)+'&ad='+encodeURIComponent(ad)+'&birim_ref='+br+'&kdv='+kdv}).then(r=>r.json()).then(data=>{ if(data.success){ showToast('Ürün kaydedildi'); urunModalKapat(); }else{ showToast('Hata: '+data.error,true); } }); }
function urunModalKapat(){ document.getElementById('urunModal').style.display='none'; }
function yeniBirimEkle(){ let yb=prompt('Yeni birim adı girin:'); if(yb){ fetch('ajax/birim_ekle.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'birim_adi='+encodeURIComponent(yb)}).then(r=>r.json()).then(data=>{ if(data.success) showToast('Birim eklendi. Ref ID: '+data.ref_id); else showToast('Hata: '+data.error,true); }); } }
document.getElementById('musteriKod').addEventListener('input',function(e){ clearTimeout(window.mt); let d=this.value.trim(); if(d.length>=2) window.mt=setTimeout(()=>musteriAra(d),500); });
document.getElementById('musteriKod').addEventListener('keypress',function(e){ if(e.key==='Enter'){ e.preventDefault(); musteriAra(this.value.trim()); } });
document.getElementById('toggleOdeme').onclick=()=>{ let tip=document.getElementById('odemeTipi').value==='Peşin'?'Veresiye':'Peşin'; document.getElementById('odemeTipi').value=tip; document.getElementById('toggleOdeme').innerHTML='💰 '+tip+' <kbd>F7</kbd>'; showToast('Ödeme tipi: '+tip); };
document.getElementById('kaydetBtn').onclick=()=>{ let fNo=document.getElementById('faturaNo').value.trim(); if(!fNo){ showToast('Fatura no giriniz!',true); return; } let mKod=document.getElementById('musteriKod').value.trim(); if(!mKod){ showToast('Müşteri kodu giriniz!',true); return; } let urunler=[], miktarlar=[], fiyatlar=[], iskontolar=[]; document.querySelectorAll('#faturaTable tbody .urun-satir').forEach(row=>{ let k=row.querySelector('.urun-kod').value.trim(); if(k){ urunler.push(k); miktarlar.push(row.querySelector('.miktar').value||0); fiyatlar.push(row.querySelector('.fiyat').value||0); iskontolar.push(row.querySelector('.iskonto').value||0); } }); if(urunler.length===0){ showToast('En az bir ürün giriniz!',true); return; } let fd=new FormData(); fd.append('fatura_no',fNo); fd.append('musteri_kod',mKod); fd.append('tarih',document.getElementById('tarih').value); fd.append('vade',document.getElementById('vade').value); fd.append('odeme_tipi',document.getElementById('odemeTipi').value); fd.append('genel_toplam',document.getElementById('genelToplam').innerText.replace(' TL','')); urunler.forEach((k,i)=>{ fd.append('urun_kod[]',k); fd.append('miktar[]',miktarlar[i]); fd.append('fiyat[]',fiyatlar[i]); fd.append('iskonto[]',iskontolar[i]); }); fetch('ajax/fatura_kaydet.php',{method:'POST',body:fd}).then(r=>r.json()).then(data=>{ if(data.success){ document.getElementById('excelBtn').style.display='inline-block'; document.getElementById('pdfBtn').style.display='inline-block'; document.getElementById('excelBtn').onclick=()=>window.location.href='exports/excel_export.php?fatura_id='+data.fatura_id; document.getElementById('pdfBtn').onclick=()=>window.location.href='exports/pdf_export.php?fatura_id='+data.fatura_id; if(data.ref_no) document.getElementById('refNoGoster').innerText=data.ref_no; showToast('Fatura kaydedildi! No: '+fNo); }else{ showToast('Hata: '+data.error,true); } }); };
document.addEventListener('keydown', (e) => { let key=e.key; if(key==='F1'||key==='F10'){ e.preventDefault(); document.getElementById('kaydetBtn').click(); } else if(key==='F2'){ e.preventDefault(); document.getElementById('musteriKod').focus(); } else if(key==='F3'){ e.preventDefault(); let fr=document.querySelector('#faturaTable .urun-kod'); if(fr) fr.focus(); } else if(key==='F7'){ e.preventDefault(); document.getElementById('toggleOdeme').click(); } else if(key==='F8'){ e.preventDefault(); showToast('Tahsilat ekranı açılacak'); } else if(key==='F9'){ e.preventDefault(); window.location.href='satis_faturasi_dokumu.php'; } else if(key==='F11'){ e.preventDefault(); openCalculator(); } else if(key==='F12'){ e.preventDefault(); urunModalGoster(); } else if(key==='Escape'){ let cm=document.getElementById('calcModal'); let um=document.getElementById('urunModal'); if(cm && cm.style.display==='flex') closeCalculator(); else if(um && um.style.display==='flex') urunModalKapat(); else if(confirm('Ana menüye dön?')) window.location.href='index.php'; } });
document.addEventListener('DOMContentLoaded',()=>{ let fr=document.querySelector('#faturaTable .urun-satir'); if(fr) attachRowEvents(fr); let fi=document.querySelector('#faturaTable .urun-kod'); if(fi) fi.focus(); });
<?php if ($duzenleData): ?>
window.addEventListener('DOMContentLoaded', () => { faturaYukle({ fatura_no:'<?= $duzenleData['fatura_no'] ?>', tarih:'<?= $duzenleData['tarih'] ?>', vade:<?= $duzenleData['vade']??0 ?>, odeme_tipi:'<?= $duzenleData['odeme_tipi'] ?>', musteri_kod:'<?= $duzenleData['musteri_kod'] ?>', musteri_adi:'<?= addslashes($duzenleData['musteri_adi']) ?>', vergi_no:'<?= $duzenleData['vergi_no'] ?>', efatura_tipi:'<?= $duzenleData['efatura_tipi'] ?>', iskonto_orani:<?= $duzenleData['iskonto_orani']??0 ?>, satirlar:<?= json_encode($duzenleData['satirlar']) ?> }); });
<?php endif; ?>
function faturaYukle(f){ document.getElementById('faturaNo').value=f.fatura_no; document.getElementById('tarih').value=f.tarih; document.getElementById('vade').value=f.vade||0; document.getElementById('odemeTipi').value=f.odeme_tipi; document.getElementById('toggleOdeme').innerHTML='💰 '+f.odeme_tipi+' <kbd>F7</kbd>'; document.getElementById('musteriKod').value=f.musteri_kod; document.getElementById('musteriBilgi').innerHTML='<strong>'+f.musteri_adi+'</strong><br>Vergi No: '+(f.vergi_no||'-')+' - '+f.efatura_tipi+'<br>🏷️ İskonto: %'+(f.iskonto_orani||0); window.musteriIskonto=f.iskonto_orani||0; let tb=document.querySelector('#faturaTable tbody'); tb.innerHTML=''; if(f.satirlar && f.satirlar.length>0){ f.satirlar.forEach(s=>{ let nr=addNewRow(); nr.querySelector('.urun-kod').value=s.urun_kod; nr.querySelector('.urun-ad').value=s.urun_adi; nr.querySelector('.birim').value=s.birim_adi||''; nr.querySelector('.miktar').value=s.miktar; nr.querySelector('.fiyat').value=s.birim_fiyat; nr.querySelector('.iskonto').value=s.iskonto_orani||0; hesaplaTutar(nr); }); }else{ addNewRow(); } genelToplamHesapla(); showToast('Fatura '+f.fatura_no+' yüklendi'); }
</script>
</body>
</html>